version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home
    image: node:8
    links:
      - "neo4j:neo4j"
    ports:
      - "3000:3000"
    working_dir: /home
    command: "nodemon -L app.js"
    environment:
      NODE_ENV: "develop"

  app.web:
    build: .
    volumes:
      - .:/home
    image: node:8
    links:
      - "neo4j:neo4j"
    ports:
      - "3000:3000"
    working_dir: /home
    command: "node app.js"
    environment:
      NODE_ENV: "develop"

  web:
    volumes:
      - .:/home
    image: node:8
    links:
      - "app.web:app.web"
    ports:
      - "8080:8080"
    working_dir: /home
    command: "npm run start.docker"


  neo4j:
    image: neo4j:3.3
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./db/dbms:/data/dbms
    environment:
      NEO4J_AUTH: "none"
